# https://www.appveyor.com/docs/appveyor-yml/

image: Visual Studio 2019

version: 1.0.{build}

configuration: Release

clone_depth: 1

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

cache:
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

build_script:
- cmd: call build.cmd

artifacts:
- path: src/bin/$(configuration)/*.vsix

deploy: off